[workspace]
members=[
  "thread_local_test",
  "tokio_with_cpp_thread",
  "speed_test",
  "option_test",
  "system_api_test",
  "hash_test",
  "lazy_init_test",
  "empty_test",
  "dylib_window_example",
  "run_dylib_example",
  "serde_example",
  "btree",
]