[package]
name = "run_dylib_example"
version = "0.1.0"
authors = ["吴宇涛 <wuyutao@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
